#for pytest complete checkout
name: CI
#on: [push]
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      #Part 4
      - name: Run tests
        run: |
          pytest ./tests/test_login_POM.py
          pytest ./tests/test_checkout_POM.py --tracing=retain-on-failure

      #Add artifects
      - name: Upload Playwright artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: playwright-artifacts
          path: test-results/
          retention-days: 30




#Part 3, 4, 5
#for pytest login
# name: CI
# # on: [push]
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt
#           playwright install --with-deps

#       #Part 4
#       - name: Run tests
#         run: pytest ./tests/test_login_POM.py
      


#Part 2
# name: CI

# on: [push]

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Say hello
#         run: echo "hello CI"
